export interface TarotCardData {
  cardNumber: number;
  name: string;
  nameZh: string;
  arcana: 'MAJOR' | 'MINOR';
  suit: string | null;
  meaningUpright: string;
  meaningReversed: string;
  meaningUprightZh: string;
  meaningReversedZh: string;
  keywords: string[];
  keywordsZh: string[];
  imageUrl: string;
}

export const TAROT_CARDS: TarotCardData[] = [
  // ====================================
  // MAJOR ARCANA (0-21)
  // ====================================
  {
    cardNumber: 0,
    name: 'The Fool',
    nameZh: '愚者',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'New beginnings, innocence, spontaneity, a free spirit. The Fool represents unlimited potential and the beginning of a journey. Embrace new experiences with an open heart.',
    meaningReversed: 'Recklessness, taken advantage of, inconsideration. You may be acting impulsively without considering consequences, or holding back from taking a necessary leap.',
    meaningUprightZh: '新的开始、天真、自发性、自由的精神。愚者代表无限的潜力和旅程的开始。以开放的心态拥抱新体验。',
    meaningReversedZh: '鲁莽、被利用、不顾后果。你可能在不考虑后果的情况下冲动行事，或者在犹豫是否要迈出必要的一步。',
    keywords: ['new beginnings', 'innocence', 'freedom', 'adventure'],
    keywordsZh: ['新开始', '天真', '自由', '冒险'],
    imageUrl: '/cards/00-the-fool.jpg',
  },
  {
    cardNumber: 1,
    name: 'The Magician',
    nameZh: '魔术师',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Manifestation, resourcefulness, power, inspired action. You have all the tools you need to succeed. Focus your will and take action to manifest your goals.',
    meaningReversed: 'Manipulation, poor planning, untapped talents. You may be using your skills for selfish purposes, or failing to recognize your own potential.',
    meaningUprightZh: '显化、足智多谋、力量、受启发的行动。你拥有成功所需的所有工具。集中你的意志并采取行动来实现你的目标。',
    meaningReversedZh: '操纵、计划不周、未开发的才能。你可能在为自私的目的使用你的技能，或者未能认识到自己的潜力。',
    keywords: ['manifestation', 'power', 'skill', 'concentration'],
    keywordsZh: ['显化', '力量', '技能', '专注'],
    imageUrl: '/cards/01-the-magician.jpg',
  },
  {
    cardNumber: 2,
    name: 'The High Priestess',
    nameZh: '女祭司',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Intuition, sacred knowledge, divine feminine, the subconscious mind. Trust your inner voice and intuition. Look beyond the obvious.',
    meaningReversed: 'Secrets, disconnected from intuition, withdrawal and silence. You may be ignoring your intuition or keeping too many secrets.',
    meaningUprightZh: '直觉、神圣知识、神圣女性、潜意识。相信你的内心声音和直觉。看清表象之外的东西。',
    meaningReversedZh: '秘密、与直觉脱节、退缩和沉默。你可能在忽视你的直觉或保守太多秘密。',
    keywords: ['intuition', 'mystery', 'subconscious', 'wisdom'],
    keywordsZh: ['直觉', '神秘', '潜意识', '智慧'],
    imageUrl: '/cards/02-the-high-priestess.jpg',
  },
  {
    cardNumber: 3,
    name: 'The Empress',
    nameZh: '皇后',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Femininity, beauty, nature, nurturing, abundance. A time of growth and fertility. Connect with your senses and the natural world.',
    meaningReversed: 'Creative block, dependence on others, smothering. You may be neglecting self-care or being overly controlling.',
    meaningUprightZh: '女性气质、美丽、自然、养育、丰富。成长和繁荣的时期。与你的感官和自然世界连接。',
    meaningReversedZh: '创造力受阻、依赖他人、窒息。你可能在忽视自我照顾或过度控制。',
    keywords: ['abundance', 'nurturing', 'fertility', 'nature'],
    keywordsZh: ['丰富', '养育', '生育力', '自然'],
    imageUrl: '/cards/03-the-empress.jpg',
  },
  {
    cardNumber: 4,
    name: 'The Emperor',
    nameZh: '皇帝',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Authority, establishment, structure, father figure. Take control and establish order. Assert your authority and set boundaries.',
    meaningReversed: 'Domination, excessive control, lack of discipline. You may be too rigid or authoritarian, or lacking necessary structure.',
    meaningUprightZh: '权威、建立、结构、父亲形象。掌控局面并建立秩序。维护你的权威并设定界限。',
    meaningReversedZh: '统治、过度控制、缺乏纪律。你可能太僵化或专制，或缺乏必要的结构。',
    keywords: ['authority', 'structure', 'control', 'stability'],
    keywordsZh: ['权威', '结构', '控制', '稳定'],
    imageUrl: '/cards/04-the-emperor.jpg',
  },
  {
    cardNumber: 5,
    name: 'The Hierophant',
    nameZh: '教皇',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Spiritual wisdom, religious beliefs, conformity, tradition. Seek guidance from established institutions or spiritual teachers. Honor tradition.',
    meaningReversed: 'Personal beliefs, freedom, challenging the status quo. You may be rebelling against tradition or questioning established beliefs.',
    meaningUprightZh: '精神智慧、宗教信仰、从众、传统。从既定机构或精神导师那里寻求指导。尊重传统。',
    meaningReversedZh: '个人信仰、自由、挑战现状。你可能在反抗传统或质疑既定信仰。',
    keywords: ['tradition', 'conformity', 'spirituality', 'education'],
    keywordsZh: ['传统', '从众', '灵性', '教育'],
    imageUrl: '/cards/05-the-hierophant.jpg',
  },
  {
    cardNumber: 6,
    name: 'The Lovers',
    nameZh: '恋人',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Love, harmony, relationships, values alignment, choices. A significant relationship or important decision. Follow your heart and values.',
    meaningReversed: 'Self-love, disharmony, imbalance, misalignment of values. You may be facing conflict in relationships or struggling with a difficult choice.',
    meaningUprightZh: '爱、和谐、关系、价值观一致、选择。重要的关系或重要的决定。跟随你的心和价值观。',
    meaningReversedZh: '自爱、不和谐、不平衡、价值观不一致。你可能面临关系冲突或在艰难的选择中挣扎。',
    keywords: ['love', 'relationships', 'choices', 'values'],
    keywordsZh: ['爱', '关系', '选择', '价值观'],
    imageUrl: '/cards/06-the-lovers.jpg',
  },
  {
    cardNumber: 7,
    name: 'The Chariot',
    nameZh: '战车',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Control, willpower, success, action, determination. You have the strength to overcome obstacles. Stay focused and drive forward.',
    meaningReversed: 'Self-discipline, opposition, lack of direction. You may be lacking focus or facing too much resistance.',
    meaningUprightZh: '控制、意志力、成功、行动、决心。你有克服障碍的力量。保持专注并向前推进。',
    meaningReversedZh: '自律、反对、缺乏方向。你可能缺乏专注或面临太多阻力。',
    keywords: ['willpower', 'determination', 'victory', 'control'],
    keywordsZh: ['意志力', '决心', '胜利', '控制'],
    imageUrl: '/cards/07-the-chariot.jpg',
  },
  {
    cardNumber: 8,
    name: 'Strength',
    nameZh: '力量',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Strength, courage, persuasion, influence, compassion. Inner strength and courage. Face challenges with grace and compassion.',
    meaningReversed: 'Inner strength, self-doubt, low energy, raw emotion. You may be struggling with self-confidence or feeling overwhelmed.',
    meaningUprightZh: '力量、勇气、说服、影响、同情。内在的力量和勇气。以优雅和同情面对挑战。',
    meaningReversedZh: '内在力量、自我怀疑、低能量、原始情绪。你可能在与自信作斗争或感到不知所措。',
    keywords: ['courage', 'inner strength', 'compassion', 'patience'],
    keywordsZh: ['勇气', '内在力量', '同情', '耐心'],
    imageUrl: '/cards/08-strength.jpg',
  },
  {
    cardNumber: 9,
    name: 'The Hermit',
    nameZh: '隐士',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Soul searching, introspection, being alone, inner guidance. Time for solitude and reflection. Look within for answers.',
    meaningReversed: 'Isolation, loneliness, withdrawal. You may be isolating yourself too much or avoiding necessary introspection.',
    meaningUprightZh: '灵魂探索、内省、独处、内在指导。独处和反思的时间。向内寻找答案。',
    meaningReversedZh: '孤立、孤独、退缩。你可能过度孤立自己或避免必要的内省。',
    keywords: ['introspection', 'solitude', 'wisdom', 'guidance'],
    keywordsZh: ['内省', '独处', '智慧', '指导'],
    imageUrl: '/cards/09-the-hermit.jpg',
  },
  {
    cardNumber: 10,
    name: 'Wheel of Fortune',
    nameZh: '命运之轮',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Good luck, karma, life cycles, destiny, a turning point. Change is coming. Accept the cycles of life and trust in destiny.',
    meaningReversed: 'Bad luck, resistance to change, breaking cycles. You may be experiencing a setback or resisting necessary change.',
    meaningUprightZh: '好运、业力、生命周期、命运、转折点。变化即将到来。接受生命的周期并相信命运。',
    meaningReversedZh: '厄运、抵制变化、打破循环。你可能正在经历挫折或抵制必要的变化。',
    keywords: ['change', 'cycles', 'fate', 'turning point'],
    keywordsZh: ['变化', '周期', '命运', '转折点'],
    imageUrl: '/cards/10-wheel-of-fortune.jpg',
  },
  {
    cardNumber: 11,
    name: 'Justice',
    nameZh: '正义',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Justice, fairness, truth, cause and effect, law. Truth and fairness will prevail. Take responsibility for your actions.',
    meaningReversed: 'Unfairness, lack of accountability, dishonesty. You may be facing injustice or avoiding taking responsibility.',
    meaningUprightZh: '正义、公平、真理、因果、法律。真理和公平将占上风。为你的行为负责。',
    meaningReversedZh: '不公平、缺乏责任、不诚实。你可能面临不公正或避免承担责任。',
    keywords: ['justice', 'fairness', 'truth', 'accountability'],
    keywordsZh: ['正义', '公平', '真理', '责任'],
    imageUrl: '/cards/11-justice.jpg',
  },
  {
    cardNumber: 12,
    name: 'The Hanged Man',
    nameZh: '倒吊人',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Pause, surrender, letting go, new perspectives. Surrender to the moment and see things from a new angle. Sometimes inaction is the answer.',
    meaningReversed: 'Delays, resistance, stalling, indecision. You may be struggling to let go or resisting necessary surrender.',
    meaningUprightZh: '暂停、臣服、放手、新视角。臣服于当下并从新角度看事物。有时不作为就是答案。',
    meaningReversedZh: '延迟、抵抗、拖延、优柔寡断。你可能在挣扎着放手或抵制必要的臣服。',
    keywords: ['surrender', 'new perspective', 'pause', 'letting go'],
    keywordsZh: ['臣服', '新视角', '暂停', '放手'],
    imageUrl: '/cards/12-the-hanged-man.jpg',
  },
  {
    cardNumber: 13,
    name: 'Death',
    nameZh: '死神',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Endings, change, transformation, transition. A major transformation is occurring. Let go of the old to welcome the new.',
    meaningReversed: 'Resistance to change, personal transformation, inner purging. You may be resisting necessary endings or transformation.',
    meaningUprightZh: '结束、变化、转变、过渡。重大转变正在发生。放下旧的以迎接新的。',
    meaningReversedZh: '抵制变化、个人转变、内在净化。你可能在抵制必要的结束或转变。',
    keywords: ['transformation', 'endings', 'change', 'transition'],
    keywordsZh: ['转变', '结束', '变化', '过渡'],
    imageUrl: '/cards/13-death.jpg',
  },
  {
    cardNumber: 14,
    name: 'Temperance',
    nameZh: '节制',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Balance, moderation, patience, purpose. Find the middle path. Practice patience and moderation.',
    meaningReversed: 'Imbalance, excess, self-healing, re-alignment. You may be experiencing extremes or struggling to find balance.',
    meaningUprightZh: '平衡、节制、耐心、目的。找到中间道路。练习耐心和节制。',
    meaningReversedZh: '不平衡、过度、自我疗愈、重新调整。你可能正在经历极端或努力寻找平衡。',
    keywords: ['balance', 'moderation', 'patience', 'harmony'],
    keywordsZh: ['平衡', '节制', '耐心', '和谐'],
    imageUrl: '/cards/14-temperance.jpg',
  },
  {
    cardNumber: 15,
    name: 'The Devil',
    nameZh: '恶魔',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Shadow self, attachment, addiction, restriction, sexuality. You may be trapped by materialism or unhealthy attachments. Recognize your chains.',
    meaningReversed: 'Releasing limiting beliefs, exploring dark thoughts, detachment. You are breaking free from restrictions or confronting your shadow.',
    meaningUprightZh: '阴影自我、依恋、成瘾、限制、性。你可能被物质主义或不健康的依恋所困。认识你的枷锁。',
    meaningReversedZh: '释放限制性信念、探索黑暗思想、超脱。你正在摆脱限制或面对你的阴影。',
    keywords: ['bondage', 'addiction', 'materialism', 'temptation'],
    keywordsZh: ['束缚', '成瘾', '物质主义', '诱惑'],
    imageUrl: '/cards/15-the-devil.jpg',
  },
  {
    cardNumber: 16,
    name: 'The Tower',
    nameZh: '高塔',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Sudden change, upheaval, chaos, revelation, awakening. A sudden disruption will bring truth. Embrace the chaos as an opportunity for growth.',
    meaningReversed: 'Personal transformation, fear of change, averting disaster. You may be avoiding necessary change or experiencing inner turmoil.',
    meaningUprightZh: '突然变化、剧变、混乱、启示、觉醒。突然的破坏将带来真相。将混乱视为成长的机会。',
    meaningReversedZh: '个人转变、害怕变化、避免灾难。你可能在避免必要的变化或经历内心的动荡。',
    keywords: ['upheaval', 'sudden change', 'chaos', 'revelation'],
    keywordsZh: ['剧变', '突然变化', '混乱', '启示'],
    imageUrl: '/cards/16-the-tower.jpg',
  },
  {
    cardNumber: 17,
    name: 'The Star',
    nameZh: '星星',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Hope, faith, purpose, renewal, spirituality. Have faith and hope for the future. You are on the right path.',
    meaningReversed: 'Lack of faith, despair, self-trust, disconnection. You may be losing hope or feeling disconnected from your purpose.',
    meaningUprightZh: '希望、信仰、目的、更新、灵性。对未来充满信心和希望。你走在正确的道路上。',
    meaningReversedZh: '缺乏信仰、绝望、自信、脱节。你可能正在失去希望或感到与你的目的脱节。',
    keywords: ['hope', 'faith', 'inspiration', 'serenity'],
    keywordsZh: ['希望', '信仰', '灵感', '宁静'],
    imageUrl: '/cards/17-the-star.jpg',
  },
  {
    cardNumber: 18,
    name: 'The Moon',
    nameZh: '月亮',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Illusion, fear, anxiety, subconscious, intuition. Things are not as they seem. Trust your intuition but beware of illusions.',
    meaningReversed: 'Release of fear, repressed emotion, inner confusion. You are confronting your fears or releasing suppressed emotions.',
    meaningUprightZh: '幻觉、恐惧、焦虑、潜意识、直觉。事情并非表面所见。相信你的直觉但要警惕幻觉。',
    meaningReversedZh: '释放恐惧、压抑的情绪、内心困惑。你正在面对你的恐惧或释放被压抑的情绪。',
    keywords: ['illusion', 'intuition', 'anxiety', 'subconscious'],
    keywordsZh: ['幻觉', '直觉', '焦虑', '潜意识'],
    imageUrl: '/cards/18-the-moon.jpg',
  },
  {
    cardNumber: 19,
    name: 'The Sun',
    nameZh: '太阳',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Positivity, fun, warmth, success, vitality. Joy and success are here. Embrace the light and warmth of life.',
    meaningReversed: 'Inner child, feeling down, overly optimistic. You may be struggling to see the positive or being unrealistically optimistic.',
    meaningUprightZh: '积极、乐趣、温暖、成功、活力。喜悦和成功就在这里。拥抱生命的光明和温暖。',
    meaningReversedZh: '内在孩童、情绪低落、过度乐观。你可能在努力看到积极面或过度乐观。',
    keywords: ['joy', 'success', 'celebration', 'positivity'],
    keywordsZh: ['喜悦', '成功', '庆祝', '积极'],
    imageUrl: '/cards/19-the-sun.jpg',
  },
  {
    cardNumber: 20,
    name: 'Judgement',
    nameZh: '审判',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Judgement, rebirth, inner calling, absolution. A time of reckoning and awakening. Answer your inner calling.',
    meaningReversed: 'Self-doubt, inner critic, ignoring the call. You may be too hard on yourself or ignoring important realizations.',
    meaningUprightZh: '审判、重生、内在召唤、赦免。清算和觉醒的时刻。回应你的内在召唤。',
    meaningReversedZh: '自我怀疑、内在批评、忽视召唤。你可能对自己太苛刻或忽视重要的领悟。',
    keywords: ['judgement', 'rebirth', 'calling', 'awakening'],
    keywordsZh: ['审判', '重生', '召唤', '觉醒'],
    imageUrl: '/cards/20-judgement.jpg',
  },
  {
    cardNumber: 21,
    name: 'The World',
    nameZh: '世界',
    arcana: 'MAJOR',
    suit: null,
    meaningUpright: 'Completion, integration, accomplishment, travel. A cycle is complete. Celebrate your achievements and prepare for new beginnings.',
    meaningReversed: 'Seeking personal closure, short-cut, delays. You may be rushing to completion or struggling to finish something.',
    meaningUprightZh: '完成、整合、成就、旅行。一个周期已经完成。庆祝你的成就并准备新的开始。',
    meaningReversedZh: '寻求个人结束、走捷径、延迟。你可能急于完成或努力完成某事。',
    keywords: ['completion', 'achievement', 'fulfillment', 'travel'],
    keywordsZh: ['完成', '成就', '圆满', '旅行'],
    imageUrl: '/cards/21-the-world.jpg',
  },

  // ====================================
  // MINOR ARCANA - WANDS (22-35)
  // ====================================
  {
    cardNumber: 22,
    name: 'Ace of Wands',
    nameZh: '权杖王牌',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Inspiration, new opportunities, growth, potential. A spark of inspiration. New creative or career opportunities are emerging.',
    meaningReversed: 'Emerging idea, lack of direction, distractions. You may be lacking motivation or facing creative blocks.',
    meaningUprightZh: '灵感、新机会、成长、潜力。灵感的火花。新的创意或职业机会正在出现。',
    meaningReversedZh: '新兴想法、缺乏方向、分心。你可能缺乏动力或面临创造力障碍。',
    keywords: ['inspiration', 'opportunity', 'growth', 'potential'],
    keywordsZh: ['灵感', '机会', '成长', '潜力'],
    imageUrl: '/cards/22-ace-of-wands.jpg',
  },
  {
    cardNumber: 23,
    name: 'Two of Wands',
    nameZh: '权杖二',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Future planning, progress, decisions, discovery. Plan for the future. Make bold decisions.',
    meaningReversed: 'Personal goals, inner alignment, fear of unknown. You may be struggling with planning or afraid to move forward.',
    meaningUprightZh: '未来规划、进步、决策、发现。为未来做规划。做出大胆的决定。',
    meaningReversedZh: '个人目标、内在一致、对未知的恐惧。你可能在规划上挣扎或害怕前进。',
    keywords: ['planning', 'decisions', 'discovery', 'vision'],
    keywordsZh: ['规划', '决策', '发现', '愿景'],
    imageUrl: '/cards/23-two-of-wands.jpg',
  },
  {
    cardNumber: 24,
    name: 'Three of Wands',
    nameZh: '权杖三',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Progress, expansion, foresight, overseas opportunities. Your plans are taking shape. Look to the horizon.',
    meaningReversed: 'Playing small, lack of foresight, unexpected delays. You may be limiting yourself or experiencing setbacks.',
    meaningUprightZh: '进步、扩展、远见、海外机会。你的计划正在成形。放眼地平线。',
    meaningReversedZh: '格局小、缺乏远见、意外延迟。你可能在限制自己或经历挫折。',
    keywords: ['expansion', 'foresight', 'progress', 'exploration'],
    keywordsZh: ['扩展', '远见', '进步', '探索'],
    imageUrl: '/cards/24-three-of-wands.jpg',
  },
  {
    cardNumber: 25,
    name: 'Four of Wands',
    nameZh: '权杖四',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Celebration, joy, harmony, relaxation, homecoming. Time to celebrate achievements. Enjoy harmony and stability.',
    meaningReversed: 'Personal celebration, inner harmony, conflict with others. You may be experiencing relationship tensions or delayed celebrations.',
    meaningUprightZh: '庆祝、喜悦、和谐、放松、归家。是时候庆祝成就了。享受和谐与稳定。',
    meaningReversedZh: '个人庆祝、内在和谐、与他人冲突。你可能正在经历关系紧张或延迟的庆祝。',
    keywords: ['celebration', 'harmony', 'homecoming', 'stability'],
    keywordsZh: ['庆祝', '和谐', '归家', '稳定'],
    imageUrl: '/cards/25-four-of-wands.jpg',
  },
  {
    cardNumber: 26,
    name: 'Five of Wands',
    nameZh: '权杖五',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Conflict, disagreements, competition, tension. Healthy competition or disagreement. Navigate conflicts constructively.',
    meaningReversed: 'Inner conflict, conflict avoidance, tension release. You may be avoiding necessary confrontation or experiencing internal struggle.',
    meaningUprightZh: '冲突、分歧、竞争、紧张。健康的竞争或分歧。建设性地处理冲突。',
    meaningReversedZh: '内心冲突、逃避冲突、释放紧张。你可能在避免必要的对抗或经历内心斗争。',
    keywords: ['conflict', 'competition', 'tension', 'diversity'],
    keywordsZh: ['冲突', '竞争', '紧张', '多样性'],
    imageUrl: '/cards/26-five-of-wands.jpg',
  },
  {
    cardNumber: 27,
    name: 'Six of Wands',
    nameZh: '权杖六',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Success, public recognition, progress, self-confidence. Victory and public acclaim. Enjoy your moment of triumph.',
    meaningReversed: 'Private achievement, self-definition, fall from grace. You may be experiencing setbacks or struggling with ego.',
    meaningUprightZh: '成功、公众认可、进步、自信。胜利和公众赞誉。享受你的胜利时刻。',
    meaningReversedZh: '私人成就、自我定义、失宠。你可能正在经历挫折或与自我斗争。',
    keywords: ['victory', 'recognition', 'success', 'pride'],
    keywordsZh: ['胜利', '认可', '成功', '自豪'],
    imageUrl: '/cards/27-six-of-wands.jpg',
  },
  {
    cardNumber: 28,
    name: 'Seven of Wands',
    nameZh: '权杖七',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Challenge, competition, protection, perseverance. Stand your ground. Defend your position.',
    meaningReversed: 'Exhaustion, giving up, overwhelmed. You may be feeling defeated or overwhelmed by opposition.',
    meaningUprightZh: '挑战、竞争、保护、坚持。坚守阵地。捍卫你的立场。',
    meaningReversedZh: '疲惫、放弃、不堪重负。你可能感到被击败或被反对压垮。',
    keywords: ['challenge', 'defense', 'perseverance', 'courage'],
    keywordsZh: ['挑战', '防御', '坚持', '勇气'],
    imageUrl: '/cards/28-seven-of-wands.jpg',
  },
  {
    cardNumber: 29,
    name: 'Eight of Wands',
    nameZh: '权杖八',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Movement, fast paced change, action, alignment. Rapid progress. Things are moving quickly.',
    meaningReversed: 'Delays, frustration, resisting change, internal alignment. You may be experiencing delays or struggling with pace.',
    meaningUprightZh: '运动、快节奏变化、行动、一致。快速进展。事情进展很快。',
    meaningReversedZh: '延迟、挫折、抵制变化、内在一致。你可能正在经历延迟或与节奏作斗争。',
    keywords: ['speed', 'action', 'movement', 'swift change'],
    keywordsZh: ['速度', '行动', '运动', '快速变化'],
    imageUrl: '/cards/29-eight-of-wands.jpg',
  },
  {
    cardNumber: 30,
    name: 'Nine of Wands',
    nameZh: '权杖九',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Resilience, courage, persistence, test of faith. Nearly there. Show resilience and courage.',
    meaningReversed: 'Inner resources, struggle, overwhelm, defensive. You may be exhausted or feeling defensive.',
    meaningUprightZh: '韧性、勇气、坚持、信念考验。快到了。展现韧性和勇气。',
    meaningReversedZh: '内在资源、挣扎、不堪重负、防御。你可能精疲力尽或感到防御。',
    keywords: ['resilience', 'persistence', 'boundaries', 'determination'],
    keywordsZh: ['韧性', '坚持', '界限', '决心'],
    imageUrl: '/cards/30-nine-of-wands.jpg',
  },
  {
    cardNumber: 31,
    name: 'Ten of Wands',
    nameZh: '权杖十',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Burden, extra responsibility, hard work, completion. Carrying heavy burdens. The end is near but effort is required.',
    meaningReversed: 'Doing it all, carrying the burden, delegation, release. You may need to delegate or let go of some responsibilities.',
    meaningUprightZh: '负担、额外责任、辛勤工作、完成。承受沉重负担。终点就在眼前但需要努力。',
    meaningReversedZh: '全部承担、承受负担、委派、释放。你可能需要委派或放下一些责任。',
    keywords: ['burden', 'responsibility', 'hard work', 'stress'],
    keywordsZh: ['负担', '责任', '辛勤工作', '压力'],
    imageUrl: '/cards/31-ten-of-wands.jpg',
  },
  {
    cardNumber: 32,
    name: 'Page of Wands',
    nameZh: '权杖侍从',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Inspiration, ideas, discovery, limitless potential. A new creative project. Embrace curiosity and enthusiasm.',
    meaningReversed: 'Newly-formed ideas, redirecting energy, self-limiting beliefs. You may be doubting your ideas or lacking direction.',
    meaningUprightZh: '灵感、想法、发现、无限潜力。一个新的创意项目。拥抱好奇心和热情。',
    meaningReversedZh: '新形成的想法、重新引导能量、自我限制信念。你可能在怀疑你的想法或缺乏方向。',
    keywords: ['enthusiasm', 'exploration', 'ideas', 'curiosity'],
    keywordsZh: ['热情', '探索', '想法', '好奇心'],
    imageUrl: '/cards/32-page-of-wands.jpg',
  },
  {
    cardNumber: 33,
    name: 'Knight of Wands',
    nameZh: '权杖骑士',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Energy, passion, inspired action, adventure, impulsiveness. Take bold action. Embrace adventure.',
    meaningReversed: 'Passion project, haste, scattered energy, delays. You may be acting impulsively or scattering your energy.',
    meaningUprightZh: '能量、激情、受启发的行动、冒险、冲动。采取大胆行动。拥抱冒险。',
    meaningReversedZh: '激情项目、匆忙、分散的能量、延迟。你可能冲动行事或分散你的能量。',
    keywords: ['action', 'passion', 'adventure', 'impulsiveness'],
    keywordsZh: ['行动', '激情', '冒险', '冲动'],
    imageUrl: '/cards/33-knight-of-wands.jpg',
  },
  {
    cardNumber: 34,
    name: 'Queen of Wands',
    nameZh: '权杖王后',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Courage, confidence, independence, social butterfly, determination. Be confident and courageous. Own your power.',
    meaningReversed: 'Self-respect, self-confidence, introverted, re-establish sense of self. You may be doubting yourself or needing to reconnect with your confidence.',
    meaningUprightZh: '勇气、自信、独立、社交蝴蝶、决心。自信和勇敢。拥有你的力量。',
    meaningReversedZh: '自尊、自信、内向、重建自我感。你可能在怀疑自己或需要重新连接你的自信。',
    keywords: ['confidence', 'independence', 'determination', 'charisma'],
    keywordsZh: ['自信', '独立', '决心', '魅力'],
    imageUrl: '/cards/34-queen-of-wands.jpg',
  },
  {
    cardNumber: 35,
    name: 'King of Wands',
    nameZh: '权杖国王',
    arcana: 'MINOR',
    suit: 'wands',
    meaningUpright: 'Natural-born leader, vision, entrepreneur, honour. Lead with vision and confidence. Take charge.',
    meaningReversed: 'Impulsiveness, haste, ruthless, high expectations. You may be too aggressive or domineering.',
    meaningUprightZh: '天生的领导者、愿景、企业家、荣誉。以愿景和信心领导。掌控局面。',
    meaningReversedZh: '冲动、匆忙、无情、高期望。你可能太激进或专横。',
    keywords: ['leadership', 'vision', 'entrepreneurship', 'boldness'],
    keywordsZh: ['领导力', '愿景', '创业', '大胆'],
    imageUrl: '/cards/35-king-of-wands.jpg',
  },

  // ====================================
  // MINOR ARCANA - CUPS (36-49)
  // ====================================
  {
    cardNumber: 36,
    name: 'Ace of Cups',
    nameZh: '圣杯王牌',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Love, new relationships, compassion, creativity. A new emotional beginning. Open your heart.',
    meaningReversed: 'Self-love, intuition, repressed emotions. You may need to focus on self-love or address repressed feelings.',
    meaningUprightZh: '爱、新关系、同情、创造力。一个新的情感开始。敞开你的心。',
    meaningReversedZh: '自爱、直觉、压抑的情绪。你可能需要专注于自爱或处理压抑的感受。',
    keywords: ['love', 'emotion', 'creativity', 'new relationship'],
    keywordsZh: ['爱', '情感', '创造力', '新关系'],
    imageUrl: '/cards/36-ace-of-cups.jpg',
  },
  {
    cardNumber: 37,
    name: 'Two of Cups',
    nameZh: '圣杯二',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Unified love, partnership, mutual attraction. A meaningful connection. Partnership and harmony.',
    meaningReversed: 'Self-love, break-ups, disharmony, distrust. You may be experiencing relationship problems or needing to focus on self-love.',
    meaningUprightZh: '统一的爱、伙伴关系、相互吸引。有意义的连接。伙伴关系和和谐。',
    meaningReversedZh: '自爱、分手、不和谐、不信任。你可能正在经历关系问题或需要专注于自爱。',
    keywords: ['partnership', 'love', 'unity', 'connection'],
    keywordsZh: ['伙伴关系', '爱', '团结', '连接'],
    imageUrl: '/cards/37-two-of-cups.jpg',
  },
  {
    cardNumber: 38,
    name: 'Three of Cups',
    nameZh: '圣杯三',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Celebration, friendship, creativity, collaborations. Celebrate with friends. Joy and community.',
    meaningReversed: "Independence, alone time, hardcore partying, 'three's a crowd'. You may be overindulging or feeling isolated.",
    meaningUprightZh: '庆祝、友谊、创造力、合作。与朋友一起庆祝。喜悦和社区。',
    meaningReversedZh: '独立、独处时间、狂欢、三人行。你可能过度放纵或感到孤立。',
    keywords: ['celebration', 'friendship', 'community', 'joy'],
    keywordsZh: ['庆祝', '友谊', '社区', '喜悦'],
    imageUrl: '/cards/38-three-of-cups.jpg',
  },
  {
    cardNumber: 39,
    name: 'Four of Cups',
    nameZh: '圣杯四',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Meditation, contemplation, apathy, reevaluation. You may be feeling dissatisfied or withdrawn. Look within.',
    meaningReversed: 'Retreat, withdrawal, checking in for alignment. You are emerging from introspection or ready to re-engage.',
    meaningUprightZh: '冥想、沉思、冷漠、重新评估。你可能感到不满或退缩。向内看。',
    meaningReversedZh: '撤退、退缩、检查对齐。你正在从内省中浮现或准备重新参与。',
    keywords: ['contemplation', 'apathy', 'meditation', 'withdrawal'],
    keywordsZh: ['沉思', '冷漠', '冥想', '退缩'],
    imageUrl: '/cards/39-four-of-cups.jpg',
  },
  {
    cardNumber: 40,
    name: 'Five of Cups',
    nameZh: '圣杯五',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Regret, failure, disappointment, pessimism. Focus on loss rather than what remains. Time to process grief.',
    meaningReversed: 'Personal setbacks, self-forgiveness, moving on. You are beginning to move past disappointment.',
    meaningUprightZh: '后悔、失败、失望、悲观。专注于失去而非剩余的东西。处理悲伤的时间。',
    meaningReversedZh: '个人挫折、自我原谅、继续前进。你正开始走出失望。',
    keywords: ['loss', 'regret', 'disappointment', 'grief'],
    keywordsZh: ['失去', '后悔', '失望', '悲伤'],
    imageUrl: '/cards/40-five-of-cups.jpg',
  },
  {
    cardNumber: 41,
    name: 'Six of Cups',
    nameZh: '圣杯六',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Revisiting the past, childhood memories, innocence, joy. Nostalgia and happy memories. Reconnect with your inner child.',
    meaningReversed: 'Living in the past, forgiveness, lacking playfulness. You may be stuck in the past or need to let go.',
    meaningUprightZh: '重温过去、童年记忆、天真、喜悦。怀旧和快乐的回忆。与你的内在孩童重新连接。',
    meaningReversedZh: '活在过去、宽恕、缺乏玩乐。你可能困在过去或需要放手。',
    keywords: ['nostalgia', 'memories', 'childhood', 'innocence'],
    keywordsZh: ['怀旧', '记忆', '童年', '天真'],
    imageUrl: '/cards/41-six-of-cups.jpg',
  },
  {
    cardNumber: 42,
    name: 'Seven of Cups',
    nameZh: '圣杯七',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Opportunities, choices, wishful thinking, illusion. Many options but some may be illusions. Choose wisely.',
    meaningReversed: 'Alignment, personal values, overwhelmed by choices. You are gaining clarity or feeling overwhelmed.',
    meaningUprightZh: '机会、选择、一厢情愿、幻觉。许多选择但有些可能是幻觉。明智地选择。',
    meaningReversedZh: '对齐、个人价值观、被选择压倒。你正在获得清晰或感到不知所措。',
    keywords: ['choices', 'illusion', 'fantasy', 'opportunities'],
    keywordsZh: ['选择', '幻觉', '幻想', '机会'],
    imageUrl: '/cards/42-seven-of-cups.jpg',
  },
  {
    cardNumber: 43,
    name: 'Eight of Cups',
    nameZh: '圣杯八',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Disappointment, abandonment, withdrawal, escapism. Walking away from something. Seek deeper meaning.',
    meaningReversed: 'Trying one more time, indecision, aimless drifting, fear of commitment. You may be hesitant to leave or moving on.',
    meaningUprightZh: '失望、放弃、退缩、逃避。离开某事。寻求更深层次的意义。',
    meaningReversedZh: '再试一次、优柔寡断、漫无目的地漂泊、害怕承诺。你可能在犹豫离开或继续前进。',
    keywords: ['disappointment', 'abandonment', 'seeking', 'withdrawal'],
    keywordsZh: ['失望', '放弃', '寻求', '退缩'],
    imageUrl: '/cards/43-eight-of-cups.jpg',
  },
  {
    cardNumber: 44,
    name: 'Nine of Cups',
    nameZh: '圣杯九',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Contentment, satisfaction, gratitude, wish come true. Emotional fulfillment. Wishes granted.',
    meaningReversed: 'Inner happiness, materialism, dissatisfaction, indulgence. You may be seeking happiness in the wrong places.',
    meaningUprightZh: '满足、满意、感激、愿望成真。情感满足。愿望实现。',
    meaningReversedZh: '内在幸福、物质主义、不满、放纵。你可能在错误的地方寻求幸福。',
    keywords: ['satisfaction', 'contentment', 'wishes', 'fulfillment'],
    keywordsZh: ['满意', '满足', '愿望', '圆满'],
    imageUrl: '/cards/44-nine-of-cups.jpg',
  },
  {
    cardNumber: 45,
    name: 'Ten of Cups',
    nameZh: '圣杯十',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Divine love, blissful relationships, harmony, alignment. Emotional and spiritual fulfillment. Happy family.',
    meaningReversed: 'Disconnection, misaligned values, struggling relationships. You may be experiencing family discord or seeking alignment.',
    meaningUprightZh: '神圣的爱、幸福的关系、和谐、一致。情感和精神满足。幸福的家庭。',
    meaningReversedZh: '脱节、价值观不一致、挣扎的关系。你可能正在经历家庭不和或寻求一致。',
    keywords: ['harmony', 'family', 'happiness', 'fulfillment'],
    keywordsZh: ['和谐', '家庭', '幸福', '圆满'],
    imageUrl: '/cards/45-ten-of-cups.jpg',
  },
  {
    cardNumber: 46,
    name: 'Page of Cups',
    nameZh: '圣杯侍从',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Creative opportunities, intuitive messages, curiosity, possibility. A new emotional or creative venture. Trust your intuition.',
    meaningReversed: 'New ideas, doubting intuition, creative blocks, emotional immaturity. You may be doubting your feelings or facing blocks.',
    meaningUprightZh: '创意机会、直觉信息、好奇心、可能性。一个新的情感或创意冒险。相信你的直觉。',
    meaningReversedZh: '新想法、怀疑直觉、创造力障碍、情感不成熟。你可能在怀疑你的感受或面临障碍。',
    keywords: ['creativity', 'intuition', 'curiosity', 'new ideas'],
    keywordsZh: ['创造力', '直觉', '好奇心', '新想法'],
    imageUrl: '/cards/46-page-of-cups.jpg',
  },
  {
    cardNumber: 47,
    name: 'Knight of Cups',
    nameZh: '圣杯骑士',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Creativity, romance, charm, imagination, beauty. A romantic proposal or creative opportunity. Follow your heart.',
    meaningReversed: 'Overactive imagination, unrealistic, jealous, moody. You may be overly idealistic or emotionally unstable.',
    meaningUprightZh: '创造力、浪漫、魅力、想象力、美。浪漫的求婚或创意机会。跟随你的心。',
    meaningReversedZh: '过度活跃的想象力、不现实、嫉妒、情绪化。你可能过于理想化或情绪不稳定。',
    keywords: ['romance', 'charm', 'creativity', 'idealism'],
    keywordsZh: ['浪漫', '魅力', '创造力', '理想主义'],
    imageUrl: '/cards/47-knight-of-cups.jpg',
  },
  {
    cardNumber: 48,
    name: 'Queen of Cups',
    nameZh: '圣杯王后',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Compassionate, caring, emotionally stable, intuitive, in flow. Nurture yourself and others. Trust your intuition.',
    meaningReversed: 'Inner feelings, self-care, self-love, co-dependency. You may need to focus on emotional self-care.',
    meaningUprightZh: '有同情心、关心、情感稳定、直觉、顺流。养育自己和他人。相信你的直觉。',
    meaningReversedZh: '内在感受、自我照顾、自爱、共同依赖。你可能需要专注于情感自我照顾。',
    keywords: ['compassion', 'intuition', 'nurturing', 'emotional'],
    keywordsZh: ['同情', '直觉', '养育', '情感'],
    imageUrl: '/cards/48-queen-of-cups.jpg',
  },
  {
    cardNumber: 49,
    name: 'King of Cups',
    nameZh: '圣杯国王',
    arcana: 'MINOR',
    suit: 'cups',
    meaningUpright: 'Emotionally balanced, compassionate, diplomatic. Master of emotions. Lead with compassion.',
    meaningReversed: 'Self-compassion, inner feelings, moodiness, emotionally manipulative. You may be suppressing emotions or being manipulative.',
    meaningUprightZh: '情感平衡、有同情心、外交。情绪的主人。以同情领导。',
    meaningReversedZh: '自我同情、内在感受、情绪化、情感操纵。你可能在压抑情绪或操纵他人。',
    keywords: ['emotional balance', 'compassion', 'diplomacy', 'wisdom'],
    keywordsZh: ['情感平衡', '同情', '外交', '智慧'],
    imageUrl: '/cards/49-king-of-cups.jpg',
  },

  // ====================================
  // MINOR ARCANA - SWORDS (50-63)
  // ====================================
  {
    cardNumber: 50,
    name: 'Ace of Swords',
    nameZh: '宝剑王牌',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Breakthroughs, new ideas, mental clarity, success. A mental breakthrough. Cut through confusion.',
    meaningReversed: 'Inner clarity, re-thinking an idea, clouded judgement. You may be experiencing confusion or need to rethink.',
    meaningUprightZh: '突破、新想法、思维清晰、成功。思维突破。穿透困惑。',
    meaningReversedZh: '内在清晰、重新思考想法、判断模糊。你可能正在经历困惑或需要重新思考。',
    keywords: ['clarity', 'breakthrough', 'truth', 'mental power'],
    keywordsZh: ['清晰', '突破', '真理', '思维力量'],
    imageUrl: '/cards/50-ace-of-swords.jpg',
  },
  {
    cardNumber: 51,
    name: 'Two of Swords',
    nameZh: '宝剑二',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Difficult decisions, weighing up options, an impasse, avoidance. You must make a choice. Remove the blindfold.',
    meaningReversed: 'Indecision, confusion, information overload. You are overwhelmed by choices or avoiding a decision.',
    meaningUprightZh: '艰难的决定、权衡选择、僵局、回避。你必须做出选择。摘下眼罩。',
    meaningReversedZh: '优柔寡断、困惑、信息过载。你被选择压倒或避免决定。',
    keywords: ['difficult choices', 'stalemate', 'avoidance', 'indecision'],
    keywordsZh: ['艰难选择', '僵局', '回避', '优柔寡断'],
    imageUrl: '/cards/51-two-of-swords.jpg',
  },
  {
    cardNumber: 52,
    name: 'Three of Swords',
    nameZh: '宝剑三',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Heartbreak, emotional pain, sorrow, grief, hurt. Deep emotional pain. Allow yourself to grieve.',
    meaningReversed: 'Negative self-talk, releasing pain, optimism, forgiveness. You are healing from heartbreak.',
    meaningUprightZh: '心碎、情感痛苦、悲伤、悲痛、伤害。深刻的情感痛苦。允许自己悲伤。',
    meaningReversedZh: '消极的自我对话、释放痛苦、乐观、宽恕。你正在从心碎中疗愈。',
    keywords: ['heartbreak', 'pain', 'sorrow', 'grief'],
    keywordsZh: ['心碎', '痛苦', '悲伤', '悲痛'],
    imageUrl: '/cards/52-three-of-swords.jpg',
  },
  {
    cardNumber: 53,
    name: 'Four of Swords',
    nameZh: '宝剑四',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Rest, relaxation, meditation, contemplation, recuperation. Take a break. Rest and recharge.',
    meaningReversed: 'Exhaustion, burn-out, deep contemplation, stagnation. You are pushing too hard or avoiding necessary rest.',
    meaningUprightZh: '休息、放松、冥想、沉思、恢复。休息一下。休息和充电。',
    meaningReversedZh: '疲惫、倦怠、深思、停滞。你推得太紧或避免必要的休息。',
    keywords: ['rest', 'relaxation', 'recovery', 'contemplation'],
    keywordsZh: ['休息', '放松', '恢复', '沉思'],
    imageUrl: '/cards/53-four-of-swords.jpg',
  },
  {
    cardNumber: 54,
    name: 'Five of Swords',
    nameZh: '宝剑五',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Conflict, disagreements, competition, defeat, winning at all costs. Conflict and tension. Choose your battles.',
    meaningReversed: 'Reconciliation, making amends, past resentment. You are making peace or holding onto grudges.',
    meaningUprightZh: '冲突、分歧、竞争、失败、不惜一切代价获胜。冲突和紧张。选择你的战场。',
    meaningReversedZh: '和解、弥补、过去的怨恨。你正在和解或抱着怨恨。',
    keywords: ['conflict', 'defeat', 'tension', 'disagreement'],
    keywordsZh: ['冲突', '失败', '紧张', '分歧'],
    imageUrl: '/cards/54-five-of-swords.jpg',
  },
  {
    cardNumber: 55,
    name: 'Six of Swords',
    nameZh: '宝剑六',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Transition, change, rite of passage, releasing baggage. Moving toward calmer waters. Leave the past behind.',
    meaningReversed: 'Personal transition, resistance to change, unfinished business. You are struggling to move on.',
    meaningUprightZh: '过渡、变化、通过仪式、释放包袱。驶向更平静的水域。把过去留在身后。',
    meaningReversedZh: '个人过渡、抵制变化、未完成的事。你正在努力前进。',
    keywords: ['transition', 'change', 'moving on', 'release'],
    keywordsZh: ['过渡', '变化', '继续前进', '释放'],
    imageUrl: '/cards/55-six-of-swords.jpg',
  },
  {
    cardNumber: 56,
    name: 'Seven of Swords',
    nameZh: '宝剑七',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Betrayal, deception, getting away with something, acting strategically. Deception or strategic thinking. Be cautious.',
    meaningReversed: 'Imposter syndrome, self-deceit, keeping secrets. You may be deceiving yourself or feeling like a fraud.',
    meaningUprightZh: '背叛、欺骗、逃脱、战略行动。欺骗或战略思维。要谨慎。',
    meaningReversedZh: '冒名顶替综合症、自我欺骗、保守秘密。你可能在欺骗自己或感觉像个骗子。',
    keywords: ['deception', 'betrayal', 'strategy', 'cunning'],
    keywordsZh: ['欺骗', '背叛', '战略', '狡猾'],
    imageUrl: '/cards/56-seven-of-swords.jpg',
  },
  {
    cardNumber: 57,
    name: 'Eight of Swords',
    nameZh: '宝剑八',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality. Feeling trapped. The bonds are self-imposed.',
    meaningReversed: 'Self-limiting beliefs, inner critic, releasing negative thoughts, open to new perspectives. You are breaking free from mental constraints.',
    meaningUprightZh: '消极思想、自我施加的限制、监禁、受害者心态。感到被困。束缚是自我施加的。',
    meaningReversedZh: '自我限制信念、内在批评、释放消极思想、对新视角开放。你正在摆脱心理束缚。',
    keywords: ['restriction', 'trapped', 'victim mentality', 'fear'],
    keywordsZh: ['限制', '被困', '受害者心态', '恐惧'],
    imageUrl: '/cards/57-eight-of-swords.jpg',
  },
  {
    cardNumber: 58,
    name: 'Nine of Swords',
    nameZh: '宝剑九',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Anxiety, worry, fear, depression, nightmares. Overwhelming anxiety and worry. Most fears are unfounded.',
    meaningReversed: 'Inner turmoil, deep-seated fears, secrets, releasing worry. You are confronting your fears or releasing anxiety.',
    meaningUprightZh: '焦虑、担心、恐惧、抑郁、噩梦。压倒性的焦虑和担心。大多数恐惧都是没有根据的。',
    meaningReversedZh: '内心动荡、根深蒂固的恐惧、秘密、释放担忧。你正在面对你的恐惧或释放焦虑。',
    keywords: ['anxiety', 'worry', 'fear', 'nightmares'],
    keywordsZh: ['焦虑', '担心', '恐惧', '噩梦'],
    imageUrl: '/cards/58-nine-of-swords.jpg',
  },
  {
    cardNumber: 59,
    name: 'Ten of Swords',
    nameZh: '宝剑十',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Painful endings, deep wounds, betrayal, loss, crisis. Rock bottom. It can only get better from here.',
    meaningReversed: 'Recovery, regeneration, resisting an inevitable end. You are recovering from a difficult ending.',
    meaningUprightZh: '痛苦的结束、深深的伤口、背叛、失去、危机。谷底。从这里只会变得更好。',
    meaningReversedZh: '恢复、再生、抵制不可避免的结束。你正在从艰难的结束中恢复。',
    keywords: ['rock bottom', 'painful ending', 'betrayal', 'crisis'],
    keywordsZh: ['谷底', '痛苦的结束', '背叛', '危机'],
    imageUrl: '/cards/59-ten-of-swords.jpg',
  },
  {
    cardNumber: 60,
    name: 'Page of Swords',
    nameZh: '宝剑侍从',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'New ideas, curiosity, thirst for knowledge, new ways of communicating. Curious and communicative. Seek truth.',
    meaningReversed: 'Self-expression, all talk and no action, haphazard action, haste. You may be acting without thinking or all talk.',
    meaningUprightZh: '新想法、好奇心、对知识的渴望、新的沟通方式。好奇和善于沟通。寻求真理。',
    meaningReversedZh: '自我表达、光说不练、草率行动、匆忙。你可能在不思考地行动或光说不练。',
    keywords: ['curiosity', 'communication', 'new ideas', 'vigilance'],
    keywordsZh: ['好奇心', '沟通', '新想法', '警惕'],
    imageUrl: '/cards/60-page-of-swords.jpg',
  },
  {
    cardNumber: 61,
    name: 'Knight of Swords',
    nameZh: '宝剑骑士',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Ambitious, action-oriented, driven to succeed, fast-thinking. Charge ahead. Act decisively.',
    meaningReversed: 'Restless, unfocused, impulsive, burn-out. You may be acting rashly or scattering your energy.',
    meaningUprightZh: '雄心勃勃、以行动为导向、渴望成功、思维敏捷。冲锋向前。果断行动。',
    meaningReversedZh: '不安、不专注、冲动、倦怠。你可能在鲁莽行事或分散你的能量。',
    keywords: ['action', 'ambition', 'driven', 'quick-thinking'],
    keywordsZh: ['行动', '雄心', '驱动', '敏捷思维'],
    imageUrl: '/cards/61-knight-of-swords.jpg',
  },
  {
    cardNumber: 62,
    name: 'Queen of Swords',
    nameZh: '宝剑王后',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Independent, unbiased judgement, clear boundaries, direct communication. Speak your truth. Think independently.',
    meaningReversed: 'Overly-emotional, easily influenced, bitchy, cold-hearted. You may be too harsh or emotionally reactive.',
    meaningUprightZh: '独立、公正的判断、清晰的界限、直接沟通。说出你的真相。独立思考。',
    meaningReversedZh: '过度情绪化、容易受影响、刻薄、冷酷。你可能太苛刻或情绪化反应。',
    keywords: ['independence', 'clarity', 'directness', 'boundaries'],
    keywordsZh: ['独立', '清晰', '直接', '界限'],
    imageUrl: '/cards/62-queen-of-swords.jpg',
  },
  {
    cardNumber: 63,
    name: 'King of Swords',
    nameZh: '宝剑国王',
    arcana: 'MINOR',
    suit: 'swords',
    meaningUpright: 'Mental clarity, intellectual power, authority, truth. Lead with logic and reason. Speak truth.',
    meaningReversed: 'Quiet power, inner truth, misuse of power, manipulation. You may be abusing your power or suppressing truth.',
    meaningUprightZh: '思维清晰、智力力量、权威、真理。以逻辑和理性领导。说出真相。',
    meaningReversedZh: '安静的力量、内在真理、滥用权力、操纵。你可能在滥用你的权力或压制真相。',
    keywords: ['mental clarity', 'authority', 'truth', 'logic'],
    keywordsZh: ['思维清晰', '权威', '真理', '逻辑'],
    imageUrl: '/cards/63-king-of-swords.jpg',
  },

  // ====================================
  // MINOR ARCANA - PENTACLES (64-77)
  // ====================================
  {
    cardNumber: 64,
    name: 'Ace of Pentacles',
    nameZh: '星币王牌',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'A new financial or career opportunity, manifestation, abundance. New material opportunity. Seeds of prosperity.',
    meaningReversed: 'Lost opportunity, lack of planning and foresight. You may be missing opportunities or lacking grounding.',
    meaningUprightZh: '新的财务或职业机会、显化、丰富。新的物质机会。繁荣的种子。',
    meaningReversedZh: '失去机会、缺乏规划和远见。你可能在错过机会或缺乏基础。',
    keywords: ['opportunity', 'prosperity', 'new venture', 'manifestation'],
    keywordsZh: ['机会', '繁荣', '新冒险', '显化'],
    imageUrl: '/cards/64-ace-of-pentacles.jpg',
  },
  {
    cardNumber: 65,
    name: 'Two of Pentacles',
    nameZh: '星币二',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Multiple priorities, time management, prioritisation, adaptability. Juggling responsibilities. Find balance.',
    meaningReversed: 'Over-committed, disorganisation, reprioritisation. You may be overwhelmed or need to reprioritize.',
    meaningUprightZh: '多重优先事项、时间管理、优先排序、适应性。兼顾责任。找到平衡。',
    meaningReversedZh: '过度承诺、混乱、重新确定优先事项。你可能不堪重负或需要重新确定优先事项。',
    keywords: ['balance', 'adaptability', 'juggling', 'flexibility'],
    keywordsZh: ['平衡', '适应性', '兼顾', '灵活性'],
    imageUrl: '/cards/65-two-of-pentacles.jpg',
  },
  {
    cardNumber: 66,
    name: 'Three of Pentacles',
    nameZh: '星币三',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Teamwork, collaboration, learning, implementation. Work together. Master your craft.',
    meaningReversed: 'Disharmony, misalignment, working alone. You may be experiencing team conflicts or working in isolation.',
    meaningUprightZh: '团队合作、协作、学习、实施。一起工作。掌握你的手艺。',
    meaningReversedZh: '不和谐、不一致、独自工作。你可能正在经历团队冲突或孤立工作。',
    keywords: ['teamwork', 'collaboration', 'skill', 'mastery'],
    keywordsZh: ['团队合作', '协作', '技能', '精通'],
    imageUrl: '/cards/66-three-of-pentacles.jpg',
  },
  {
    cardNumber: 67,
    name: 'Four of Pentacles',
    nameZh: '星币四',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Saving money, security, conservatism, scarcity, control. Holding on tightly. Fear of loss.',
    meaningReversed: 'Over-spending, greed, self-protection. You may be too controlling or experiencing financial insecurity.',
    meaningUprightZh: '存钱、安全、保守、稀缺、控制。紧紧抓住。害怕失去。',
    meaningReversedZh: '过度消费、贪婪、自我保护。你可能太控制或经历财务不安全。',
    keywords: ['control', 'security', 'conservation', 'possession'],
    keywordsZh: ['控制', '安全', '保守', '占有'],
    imageUrl: '/cards/67-four-of-pentacles.jpg',
  },
  {
    cardNumber: 68,
    name: 'Five of Pentacles',
    nameZh: '星币五',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Financial loss, poverty, lack mindset, isolation, worry. Hard times. Seek help and support.',
    meaningReversed: 'Recovery from financial loss, spiritual poverty. You are recovering or need to focus on inner wealth.',
    meaningUprightZh: '经济损失、贫困、匮乏心态、孤立、担忧。艰难时期。寻求帮助和支持。',
    meaningReversedZh: '从经济损失中恢复、精神贫困。你正在恢复或需要专注于内在财富。',
    keywords: ['hardship', 'loss', 'isolation', 'worry'],
    keywordsZh: ['困难', '损失', '孤立', '担忧'],
    imageUrl: '/cards/68-five-of-pentacles.jpg',
  },
  {
    cardNumber: 69,
    name: 'Six of Pentacles',
    nameZh: '星币六',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Giving, receiving, sharing wealth, generosity, charity. Give and receive. Share your abundance.',
    meaningReversed: 'Self-care, unpaid debts, one-sided charity. You may be giving too much or not receiving enough.',
    meaningUprightZh: '给予、接收、分享财富、慷慨、慈善。给予和接收。分享你的丰富。',
    meaningReversedZh: '自我照顾、未偿债务、单方面慈善。你可能给予太多或接收不够。',
    keywords: ['generosity', 'charity', 'sharing', 'giving'],
    keywordsZh: ['慷慨', '慈善', '分享', '给予'],
    imageUrl: '/cards/69-six-of-pentacles.jpg',
  },
  {
    cardNumber: 70,
    name: 'Seven of Pentacles',
    nameZh: '星币七',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Long-term view, sustainable results, perseverance, investment. Patience required. Your efforts will pay off.',
    meaningReversed: 'Lack of long-term vision, limited success or reward. You may be impatient or seeing little progress.',
    meaningUprightZh: '长远眼光、可持续结果、毅力、投资。需要耐心。你的努力会有回报。',
    meaningReversedZh: '缺乏长远眼光、有限的成功或回报。你可能不耐烦或看到进展甚微。',
    keywords: ['patience', 'investment', 'long-term', 'perseverance'],
    keywordsZh: ['耐心', '投资', '长期', '毅力'],
    imageUrl: '/cards/70-seven-of-pentacles.jpg',
  },
  {
    cardNumber: 71,
    name: 'Eight of Pentacles',
    nameZh: '星币八',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Apprenticeship, repetitive tasks, mastery, skill development. Master your craft. Practice makes perfect.',
    meaningReversed: 'Self-development, perfectionism, misdirected activity. You may be too focused on perfection or wasting effort.',
    meaningUprightZh: '学徒、重复性任务、精通、技能发展。掌握你的手艺。熟能生巧。',
    meaningReversedZh: '自我发展、完美主义、误导的活动。你可能过于专注于完美或浪费努力。',
    keywords: ['mastery', 'skill', 'dedication', 'craftsmanship'],
    keywordsZh: ['精通', '技能', '奉献', '工艺'],
    imageUrl: '/cards/71-eight-of-pentacles.jpg',
  },
  {
    cardNumber: 72,
    name: 'Nine of Pentacles',
    nameZh: '星币九',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Abundance, luxury, self-sufficiency, financial independence. Enjoy your success. You have earned it.',
    meaningReversed: 'Self-worth, over-investment in work, hustling. You may be too focused on work or struggling with self-worth.',
    meaningUprightZh: '丰富、奢华、自给自足、财务独立。享受你的成功。你赢得了它。',
    meaningReversedZh: '自我价值、过度投资于工作、奔波。你可能过于专注于工作或与自我价值作斗争。',
    keywords: ['abundance', 'luxury', 'independence', 'self-sufficiency'],
    keywordsZh: ['丰富', '奢华', '独立', '自给自足'],
    imageUrl: '/cards/72-nine-of-pentacles.jpg',
  },
  {
    cardNumber: 73,
    name: 'Ten of Pentacles',
    nameZh: '星币十',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Wealth, financial security, family, long-term success, contribution. Lasting prosperity. Legacy and inheritance.',
    meaningReversed: 'The dark side of wealth, financial failure or loss. You may be experiencing financial instability or family issues.',
    meaningUprightZh: '财富、财务安全、家庭、长期成功、贡献。持久的繁荣。遗产和继承。',
    meaningReversedZh: '财富的阴暗面、财务失败或损失。你可能正在经历财务不稳定或家庭问题。',
    keywords: ['wealth', 'legacy', 'family', 'long-term success'],
    keywordsZh: ['财富', '遗产', '家庭', '长期成功'],
    imageUrl: '/cards/73-ten-of-pentacles.jpg',
  },
  {
    cardNumber: 74,
    name: 'Page of Pentacles',
    nameZh: '星币侍从',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Manifestation, financial opportunity, skill development. A new venture or learning opportunity. Stay grounded.',
    meaningReversed: 'Lack of progress, procrastination, learn from failure. You may be lacking focus or procrastinating.',
    meaningUprightZh: '显化、财务机会、技能发展。一个新的冒险或学习机会。保持脚踏实地。',
    meaningReversedZh: '缺乏进展、拖延、从失败中学习。你可能缺乏专注或在拖延。',
    keywords: ['opportunity', 'learning', 'manifestation', 'grounded'],
    keywordsZh: ['机会', '学习', '显化', '脚踏实地'],
    imageUrl: '/cards/74-page-of-pentacles.jpg',
  },
  {
    cardNumber: 75,
    name: 'Knight of Pentacles',
    nameZh: '星币骑士',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Hard work, productivity, routine, conservatism. Steady progress. Stay committed.',
    meaningReversed: 'Self-discipline, boredom, feeling stuck, perfectionism. You may be too rigid or feeling stagnant.',
    meaningUprightZh: '努力工作、生产力、常规、保守。稳步前进。保持承诺。',
    meaningReversedZh: '自律、无聊、感觉困住、完美主义。你可能太僵化或感到停滞。',
    keywords: ['hard work', 'routine', 'reliability', 'patience'],
    keywordsZh: ['努力工作', '常规', '可靠性', '耐心'],
    imageUrl: '/cards/75-knight-of-pentacles.jpg',
  },
  {
    cardNumber: 76,
    name: 'Queen of Pentacles',
    nameZh: '星币王后',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Nurturing, practical, providing financially, a working parent. Nurture and provide. Balance work and home.',
    meaningReversed: 'Financial independence, self-care, work-home conflict. You may be struggling to balance or need self-care.',
    meaningUprightZh: '养育、实用、经济上提供、工作的父母。养育和提供。平衡工作和家庭。',
    meaningReversedZh: '财务独立、自我照顾、工作家庭冲突。你可能在努力平衡或需要自我照顾。',
    keywords: ['nurturing', 'practicality', 'abundance', 'security'],
    keywordsZh: ['养育', '实用性', '丰富', '安全'],
    imageUrl: '/cards/76-queen-of-pentacles.jpg',
  },
  {
    cardNumber: 77,
    name: 'King of Pentacles',
    nameZh: '星币国王',
    arcana: 'MINOR',
    suit: 'pentacles',
    meaningUpright: 'Wealth, business, leadership, security, discipline, abundance. Master of material realm. Build lasting wealth.',
    meaningReversed: 'Financially inept, obstinate, flashy. You may be overly materialistic or financially reckless.',
    meaningUprightZh: '财富、商业、领导力、安全、纪律、丰富。物质领域的主人。建立持久的财富。',
    meaningReversedZh: '财务无能、固执、炫耀。你可能过于物质主义或财务鲁莽。',
    keywords: ['wealth', 'business', 'abundance', 'security'],
    keywordsZh: ['财富', '商业', '丰富', '安全'],
    imageUrl: '/cards/77-king-of-pentacles.jpg',
  },
];
